### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Jak2k** [BezPowell/better-web-alliance#4]

**Comment by BezPowell** [comment]
Sorry I've taken a while to respond to this; I do not use my mobile phone very frequently and Github's recent change to requiring 2FA means I'm a bit behind on any interactions using the web interface.

As the main purpose of the site is to provide a list of useful resources, I haven't really thought about it requiring 'maintenance' in the same way as a library used by other projects. It's been a while since I've added anything to the site, but I'm hoping the resources there (and the message behind them) are still useful.

I'm always open to new suggestion for resources to add to the site, so if there's anything you think would be useful to other developers please feel free to suggest it! The same with any suggestions for other features.

**Comment by Jak2k** [comment]
- The resources section is divided into small categories with just a few items each. I think moving all the items to `/resources` would be clearer
- It's not obvious how to add a site to `/sites`. An *Add*-link that goes to an issue-template on GiHub would be cool.
- The design looks a bit outdated. Of course this is subjective, but I think choosing a sans-font for titles and centering the contact form with an added border would help a lot.
- Using `<em>` and `<b>` to highlight parts of the texts would make it easier to skim the texts.
- The sitemap-link is broken and it may be better placed in the `<head>` as it's mainly for search engines.

**Comment by BezPowell** [comment]
Thank you for the suggestions. I've fixed the sitemap link and will look at the others over the coming few months. I agree that a new design would be nice, as that was only ever intended to be an interim set of styles to go live with.
